Makefile, urth/dashboard/converter/__init__.py, urth/dashboard/nbexts/bundle_handler.py
Opted for a folder named "local_dashboards" so it remains visible
in the tree, but still contains all the generated local dashboards.
=> [issue: 9] Converter should put converted files into "dot" folder

urth/dashboard/converter/static/urth/dashboard.js, urth_dash_js/notebook/dashboard-common/error-log.js
Issue #15 .    
Wait for one of the possible kernel created events before registering
the Error handler.
=> [issue 15] Race condition in error-log enable with kernel readiness

etc/notebooks/stream_demo/meetup-streaming.ipynb
Also, fix issue with paper-toggle-button by pulling backlevel version. (See https://github.com/PolymerElements/paper-toggle-button/issues/54)
=> Update branch for globe to pull from master.

.gitignore, etc/notebooks/stream_demo/meetup-streaming.ipynb, etc/notebooks/taxi_demo/taxi_dashboard.ipynb, etc/notebooks/test/test_layout_declarativewidgets.ipynb, urth/dashboard/converter/static/main.js
To fix Safari and Firefox support in declarative widgets (jupyter-incubator/declarativewidgets#21) the path passed to the widget init function needed to change (jupyter-incubator/declarativewidgets#28).
This PR contains the path change in the dashboard `main.js` and a test notebook. It should not be merged until after the PR above is merged for widgets.
=> Compatibility update with widgets for Safari / Firefox support

urth_dash_js/notebook/deploy-menu/deploy-menu.js
The save_notebook call winds up returning a null / undefined instead of a promise. Check to see if we're actually getting a promise back or not before invoking then(). (Maybe should be fixed upstream in notebook JS to always return the promise.)
=> Deploy As -> Local fails if notebook is read only

.gitignore, etc/notebooks/community_sentiment_demo/community_sentiment_demo.ipynb, etc/notebooks/community_sentiment_demo/widgets/urth-timeline/bower.json, etc/notebooks/community_sentiment_demo/widgets/urth-timeline/urth-timeline.html
Creates a dashboard for analyzing community sentiment around open source projects.
=> [issue 14]: Initial prototype of sentiment dashboard

urth/dashboard/converter/static/main.js, urth/dashboard/converter/static/urth/dashboard.js
Works in conjunction with [this PR](https://github.com/jupyter-incubator/declarativewidgets/pull/52) from the declarativewidgets repo.
Fixes issue #38.
=> [Issue 38] Wait for widgets loaded promise before running cells

urth_dash_js/notebook/dashboard-view/dashboard-actions.js, urth_dash_js/notebook/dashboard-view/dashboard-view.css, urth_dash_js/notebook/dashboard-view/dashboard.js
Instead of cloning cell contents to show in the hidden cells area,
absolutely position them to put them below the Dashboard area.
This also allows us to show animated transitions when moving the
cells.
Fixes issue #42
:cow: :octopus:
=> [Issue 42] Absolutely position hidden dashboard cells

urth_dash_js/notebook/dashboard-view/dashboard.js
Fixes a couple places where we weren't waiting for resize transition
to end before calling the toplevel `onResize` callback.
=> [Issue 57] Resize cell contents after cell transition

test/test_convert.py, urth/dashboard/converter/__init__.py
Removed looking for a notebook's specific bower components and just copy the entire directory. As the declarative widget project looks at refactoring `urth-core-import`, we will see if there is any restructuring that will serve a better solution for installing imports.
=> [Issue 80]: Removed optimization of selecting notebook specific dependencies

Makefile, setup.py, urth/dashboard/_version.py
WIP until we decide naming.
Versioning follows what notebook and other Jupyter components use. At first major/minor/patch release time, a manual commit is added to remove the `dev` part of the version tuple (0.1.0). 
https://github.com/jupyter/notebook/commit/b55157282a2f56be589eb9c2558e7840e1df552c
That commit is branched (0.1.x) and  tagged (0.1.0) for package build and release on pypi. Then another commit is immediately pushed on master with the `dev` added back and the appropriate part of the version number bumped (0.2.0.dev).
Important patches are made against the major/minor branch and tagged at release time. The same patches are put in master.
=> Adopt jupyter versioning approach, package name

urth_dash_js/notebook/dashboard-view/dashboard-actions.js, urth_dash_js/notebook/dashboard-view/view-menu.html
Take "view" out of the view menu's actions. For #123.
=> [issue 123] View menu items and toolbar switcher should use consistent naming

.gitignore, .travis.yml, Makefile, README.md, etc/notebooks/system-test/Basic.ipynb, package.json, system-test/bin/kill-selenium.sh, system-test/bin/run-selenium.sh, system-test/dashboard-buttons-test.js, system-test/dashboard-menu-test.js, system-test/utils/boilerplate.js, system-test/utils/dashboard.js
Make targets now include `system-test-remote` and `system-test-local` for running system tests on travis and locally. 
=> [Issue 116]: Add system tests

setup.py
* Ensure config directories exist (fixes error)
* Use ConfigManager for server config too
Issue #153
=> Improve config management on install

urth_dash_js/notebook/dashboard-view/dashboard-actions.js
The `actions.register` should return the prefix+action names mangled
correctly, and in 4.1 we changed the prefix/name separator for `:`
instead of `.` which of course broke things.
-- 
Should fix #158
=> Fix dashboard add_toolbar_buttons

urth_dash_js/notebook/dashboard-view/dashboard-view.js
Retains backward compt with 4.0.x
Fixes #159
=> Fix gridstack -> jquery-ui map for notebook 4.1

setup.py
Reverts JSON config switch made in issue #153 so that we don't clobber declarativewidgets or other projects. Does retain the fix for the missing config directories.
Will revisit #153 when we're ready to make the change en masse across all the associated extension projects. Don't want to block 0.3.0 on this which should primarily be about notebook 4.1 compatibility and for the separation of bundlers (#151).
=> Revert to old server config technique

etc/notebooks/got_scotch_demo/scotch_dashboard_declarative.ipynb
Use declarative widgets for this version of scotch demo. However, there's an issue with resetting table selection.
(Issue: Select a scotch X from the suggestion table, then pick a new scotch A from the drop down. Expected is that the chart should only show this new scotch A. But the bug is that the chart still shows both this new scotch A and the scotch X previously selected from table). This issue is being worked on <a href="https://github.com/jupyter-incubator/declarativewidgets/issues/163">here</a>.
=> Fix Issue #141 part 2

etc/notebooks/community_sentiment_demo/community_sentiment_demo.ipynb, etc/notebooks/sentiment_boilerplate_demo/sentiment_boilerplate_demo.ipynb
Updated the sentiment notebooks to use the new `urth-core-channel` element instead of the global. Also, fixed some markdown issues.
@Lull3rSkat3r is aware of an existing bug in the boilerplate notebook.
Fixes issue #170 
Dependent on jupyter-incubator/declarativewidgets#179
=> Update sentiment notebooks for channel changes.

Makefile
Merge after jupyter-incubator/declarativewidgets#167 lands and #166 lands in dashboards.
=> Activate widgets in dev-with-widgets

jupyter_dashboards/nbextension/notebook/dashboard-common/error-log.js
IPython.utils is not available outside of notebook (e.g., in Thebe)
=> Fallback on logging raw exceptions to console

etc/notebooks/stream_demo/meetup-streaming.ipynb
=> [issue: 186] Incorrect urth-core-function syntax in meetup-streaming

.travis.yml, system-test/dashboard-buttons-test.js, system-test/dashboard-menu-test.js, system-test/utils/dashboard.js
* Account for chrome always prompt to save notebooks on tab close
* Account for UI changes due to report mode
No new tests for report mode added. Keeping the smoke test simple. (It's already brittle enough.)
Fix #219
=> [issue 219] Restore selenium tests

jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.js, jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js
Problem: Transition between states like notebook -> report -> grid -> report and notice the empty cells aren't hidden
This is because we set min-height in CSS
This ensures empty cells are zero height
=> Report fix: proper empty cell computation

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.js
1. http://jupyter.cloudet.xyz/
2. Make a new notebook
3. Put print('hi') in a cell
4. Switch to **report** layout
5. Save
6. Refresh
7. Toolbar defaults to grid layout
Tested with v0.5.0
=> Notebook with report layout opens with button set to grid

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js, jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js
Will provide reproducible test case and animation soon. Just noting that I hit the bug working on a notebook that I can't share.
Steps to reproduce:
1. Start a new notebook
2. print something.
3. Switch to report layout. Confirm the cell is included in the visible set.
4. Save
5. Switch to notebook.
6. Clear all output.
7. Save.
8. Refresh
9. Switch to report layout.
10. Notice the cell that was in the report layout is now marked as hidden.
Does not affect grid mode.
=> Cells are lost from report layout after refresh

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.js, jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata-compatibility.js, jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js, jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js, jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.js, jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js, jupyter_dashboards/nbextension/notebook/dashboard-view/object-util.js, jupyter_dashboards/nbextension/notebook/main.js, system-test/utils/dashboard.js
=> [Issue 243] Move to new metadata spec

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata-compatibility.js
=> [Issue 256] When converting, hide grid cells that have empty dashboards metadata

CHANGELOG.md, README.md, docs/source/development.md, docs/source/index.rst, docs/source/metadata.md, docs/source/summary-changes.md, etc/notebooks/index.ipynb, etc/notebooks/resizable_widgets_tutorial/resizable_widgets.ipynb, jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata-compatibility.js, jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js, package.json, setup.py
See #285 
The `dashboards` repo has been migrated from `jupyter-incubator` organization to `jupyter`. Make appropriate changes in documentation and strings.
=> #285 Replace references to jupyter-incubator with jupyter for dashboards only

Makefile, jupyter_dashboards/nbextension/notebook/dashboard-common/dashboard-common.css
Comment in file said overflow was done to allow popover widgets
to display properly. When I change the styling, both ipwidget
and declarative widget popover still appear to show properly
in my limited test. Other content clips at the dashboard cell
boundaries, as expected and desired.
=> Fix #283: Clip at grid cell boundaries

docs/source/index.rst
The markdown links for dashboards_bundlers and dashboards_server were not rendering properly for some reason.
=> Update index.rst markdown links
