jupyter/dashboards

urth/dashboard/converter/__init__.py
urth/dashboard/nbexts/bundle_handler.py

Allows the user to increase thebe.tpl's complexity without breaking local test deployment.

Default to local.tpl when deploying as Local Dashboard, if present

---

urth/dashboard/nbexts/bundle_handler.py

Fix double base_url

---

urth_dash_js/notebook/dashboard-view/dashboard-view.js
urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/dashboard-view/polymer-support.js

Listen for and track Polymer elements using the
`iron-resizable-behavior`, then notify them if their parent cell has
been resized.

[Issue 12] Notify any Polymer elements when cell has resized

---

urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/deploy-menu/deploy-menu.js

When converting a notebook to a dashboard, it should either automatically save or prompt for save before executing the conversion. Problem is there's a race condition with the invocation of save and knowing when the save has finished. I don't think it returns a promise. Maybe there's a jupyter event?

Save before converting

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js

It should not scroll to the bottom.

"Run All" from dashboard view scrolls page to bottom

---

urth_dash_js/notebook/dashboard-view/dashboard.js

... since it re-orders cells' DOM nodes.
Fixes #7
Fixes #26
:cow:

[Issue 7] Disable Gridstack's single-column mode

---

.travis.yml
Makefile
package.json

It runs a container and runs our node scripts into a volume-mounted folder.
This removes node and bower requirements from host machine.

[Issue 22] Added `js` target to Makefile.

---

.gitignore
etc/notebooks/resizable_widgets_tutorial/resizable_widgets.ipynb

[Issue 27] Tutorial showing impl of resizable widgets

---

urth_dash_js/notebook/dashboard-view/dashboard-view.css
urth_dash_js/notebook/dashboard-view/dashboard.js

[Issue 53] Show cell bounds even when contents overflow

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js

Need to trigger resize-header.Page event like the show/hide header menu items do
Fixes #62

Fix page area resize bug when header shows/hides

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js

Removes left over styling when going into dashboard mode.

[Issue 64]: Removed height of notebook element when exiting dashboard

---

urth_dash_js/notebook/dashboard-view/dashboard.js

Added `dragstop` to events that cause a dashboard resize.

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js
urth_dash_js/notebook/dashboard-view/dashboard.js

Also, moved unsetting 'height' when exiting Dashboard to destroy().
Fixes #68 
:cow:

[Issue 68] Only set 'height' when in Layout Dashboard mode.

---

urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/dashboard-view/polymer-support.js

And some additional Gridstack cleanup.
Fixes #57 
:cow: :arrow_right: :meat_on_bone:

[Issue 57] Tell correct node to resize when loading Dashboard.

---

etc/notebooks/meetup_outreach_demo/upcoming-meetups.html

[Issue 83] Changed upcoming meetups link color in meetup outreach notebook.

---

urth/dashboard/converter/static/urth/dashboard.js

Discovered this in my 4.x port testing. I thought it had to do with how the new thebe based on the 4.x notebook behaves, but I just hit it in master too.
1. Run without widgets installed.
2. Deploy scotch dashboard locally.
3. Notice it doesn't load.
4. Look in console to see kernel not ready messages.
I don't know if we introduced this recently or not, but it appears that we've have a race condition between the kernel being ready and sending it commands to execute. I thought Thebe would queue these things up, but I suspect our explicit call to start the kernel in `initThebe` is breaking that queueing mechanism some how. We now need to wait for the kernel ready event before we try sending any commands.
Fix is pretty simple: listen for that event and avoid resolving the problem until it's …

Race condition between execute all in thebe and kernel ready

---

etc/notebooks/meetup_outreach_demo/upcoming-meetups.html

Instead of importing Font Awesome into our new Polymer element,
let's just use unicode.
Fixes #88 
:cow:

[Issue 88] Fix arrows in Upcoming Meetups element.

---

urth/dashboard/converter/jinja_templates/thebe.tpl

Add check for layout metadata during convert

---

etc/notebooks/stream_demo/meetup-streaming.ipynb

Correct the contents of etc/notebooks/stream_demo/meetup-streaming.ipynb

[issue 34] Incorrect conversion of HTML within markdown cell

---

etc/notebooks/meetup_outreach_demo/meetup-outreach.ipynb
etc/notebooks/meetup_outreach_demo/upcoming-meetups.html
urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/dashboard-view/polymer-support.js

Revert `Polymer.dom` call when handling events.
Add resizing check to upcoming meetups Polymer element.
:chicken:

[Issue 57] Handle resize directly in upcoming meetups element.

---

urth_dash_js/notebook/dashboard-view/dashboard.js

Remove `batch`, since we're no longer saving, just marking dirty.
Fixes #56 
:cow:

[Issue 56] Show individual hidden cells at full width.

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.css
urth_dash_js/notebook/dashboard-view/dashboard-actions.js

[Issue 54] Add toolbar button group for switching dashboard view.

---

etc/notebooks/meetup_outreach_demo/meetup-outreach.ipynb

[Issue 96] Properly filter PROD_TOPIC from incoming RSVPs

---

bower.json
urth_dash_js/notebook/dashboard-view/dashboard-view.js
urth_dash_js/notebook/dashboard-view/help.html

[Issue 63] Show help text in dashboard layout view.

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.css
urth_dash_js/notebook/dashboard-view/dashboard-actions.js
urth_dash_js/notebook/dashboard-view/dashboard-view.js
urth_dash_js/notebook/dashboard-view/sub-menu.html
urth_dash_js/notebook/dashboard-view/view-menu.html

Refactored how dashboard menu items are created.
Fixes #99 
:chicken:
This PR depends on PR #101

[Issue 99] Move 'show/hide all cells' toolbar buttons into the 'Cell > Dashboard' submenu.

---

test/resources/no_imports.ipynb
test/test_convert.py
urth/dashboard/converter/__init__.py

[Issue 84]: Added optimization to not copy bower_components

---

urth_dash_js/notebook/dashboard-view/help.html

Updated based on feedback from @parente.
:chicken:

[Issue 63] Update help text summary and add show/hide.

---

urth/dashboard/converter/static/urth/dashboard.js

Spawn container before requesting kernel in tmpnb

---

etc/notebooks/meetup_outreach_demo/dynamic-list.html
etc/notebooks/meetup_outreach_demo/meetup-outreach.ipynb

[Issue 109] Show meetup RSVPed to in candidate list

---

etc/notebooks/index.ipynb

[Issue 41]: Added section for sentiment notebook in index.ipynb

---

README.md

[Issue 100]: Added doc message telling for deploying widgets

---

.travis.yml
Makefile
README.md
urth/dashboard/nbexts/bundle_handler.py

[Issue 118]: Added python 2.7 support

---

Makefile

Need to use sh, not bash, as init process in dev
/cc @Lull3rSkat3r

Fix regression, kernels won't start

---

Makefile
setup.py

Some metadata cleanup too in setup.py
/cc @lbustelo

Make targets for pypi release

---

etc/notebooks/bokeh_demo/bokeh_demo.ipynb

Second pass at PR #120
Fixes #86

[issue 86] Create a demo that uses other widget libraries in a dashboard

---

Makefile

Moved docker commands to run in bash and ipython to run in sh.

[Issue 118]: Fixed broken kernels for multiple python versions

---

README.md

Update README with pip install step.

Prepare for 0.1.0 release

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js
urth_dash_js/notebook/dashboard-view/dashboard-view.js
urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/dashboard-view/sub-menu.html

[Issue 132]: Add stacked layout option when showing all cells.

---

urth_dash_js/notebook/dashboard-view/sub-menu.html

[Issue 132]: Fixed titles for add all cell buttons

---

.travis.yml
Makefile

Make teardown a make target too for consistency

Fix missing sys test setup command

---

urth_dash_js/notebook/dashboard-view/dashboard-actions.js
urth_dash_js/notebook/dashboard-view/dashboard-view.css
urth_dash_js/notebook/dashboard-view/dashboard.js
urth_dash_js/notebook/dashboard-view/help.html

[Issue 131] Show code on hover in 'Layout Dashboard' mode

---

urth/dashboard/converter/static/main.js

Fixes #142, for declarativewidgets 0.2.x support

Shim WidgetManager and WidgetModel when deploying

---

urth_dash_js/notebook/dashboard-view/dashboard-view.css
urth_dash_js/notebook/dashboard-view/dashboard.js

Cap height. Remove show/hide button.
Fixes #131 
:cow:

[Issue 131] Always show code in hidden cells area.

---

urth/dashboard/converter/jinja_templates/thebe.tpl
urth_dash_js/notebook/dashboard-common/dashboard-common.css

Fixes issue where, when going back to notebook mode from dashboard, styling was still applied.

Only apply common styling when in dashboard mode.

---

etc/notebooks/got_scotch_demo/scotch_dashboard.ipynb

Fixes Issue #141 part 1: Add more instructions in scotch demo nb

---

urth_dash_js/notebook/dashboard-view/dashboard-view.css

[Issue 174] Hide error messages in dashboard cells when in dashboard view

---

CHANGELOG.md

Update changelog for 0.4.0

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css

Applies to Notebook version 4.1+
Fixes #182

[Issue 182] Fix selected cell styling in dashboard view.

---

Makefile
bower.json

* Fix incompatibility with gridstack
* Fix make clean bower_components path

Pin lodash to < 4.0

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js

Also, remove urlArgs (everything after '?') from toUrl() result.
Ref #181

Don't include extension in require.js paths config

---

bower.json
jupyter_dashboards/nbextension/notebook/dashboard-common/gridstack-custom.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js

Fixes #17.
Unfortunately, only fixes part of #18.

Update to gridstack 0.2.4

---

jupyter_dashboards/nbextension/notebook/dashboard-common/dashboard-common.css

[Issue 188] Always hide anchor-link element.

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js

[Issue 191] Reduce width of background input so it doesn't overflow dashboard cell in layout view.

---

etc/notebooks/bokeh_demo/bokeh_demo.ipynb

[issue: 200] Fix bokeh inline JS

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js

[Issue 198] Scroll the layout view when dragging a cell to the top or bottom

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js

Add to top
Add to bottom
Add relative to notebook position
Resolves #199

[Issue 199] Add extra hidden cell add buttons

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js

[Issue 208] Show buttons to move to top and bottom on grid cells.

---

Makefile

Match what's used in dashboard_server

Bump dev image version to notebook 4.1

---

README.md
jupyter_dashboards/__init__.py

[issue: 215] Support new install mechanism in nb 4.2

---

README.md
jupyter_dashboards/__init__.py
jupyter_dashboards/extensionapp.py

Reduce number of commands required to install / enable for the common use case.
Similar to https://github.com/jupyter-incubator/contentmanagement/pull/36

Enable quick setup and removal

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.js

Don't update the stateful visibility vars twice on notebook load with ?dashboard set
Follow up on #211

Fix state tracking for header and toolbar

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js

[Issue 222] Fix error on report layout with no metadata

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.js
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.css
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js

[Issue 223] Properly read and set notebook metadata

---

jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.js

This is a collapse hidden cell edge case fix.

Report fix: Hiding a cell preceding a collapsed group should merge it with the collapsed group

---

Makefile
jupyter_dashboards/nbextension/notebook/main.js

Replace dashboard layout metadata in copied cells with "hidden."
This unfortunately does affect the Cut operation as well.
Fixes #202

[Issue: 202] Multiple pasted cells get the same layout

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css

Hide urth-viz-error in dashboard views

---

jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js
jupyter_dashboards/nbextension/notebook/dashboard-view/help.html

Always reset to shown, fixes #239

Fix show code checkbox state

---

jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.js

Save grid metadata on hide

---

jupyter_dashboards/nbextension/notebook/dashboard-common/dashboard-common.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-actions.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-metadata.js
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.css
jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard-view.js
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.css
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/grid/layout.js
jupyter_dashboards/nbextension/notebook/dashboard-view/layout/report/layout.css
jupyter_dashboards/nbextension/notebook/dashboard-view/sub-menu.html
jupyter_dashboards/nbextension/notebook/dashboard-view/view-menu.html
jupyter_dashboards/nbextension/notebook/dashboard-view/view-toolbar-buttons.html
system-test/utils/dashboard.js

[Issue 243] Remove "urth" references from HTML & CSS

---

Makefile
etc/notebooks/got_scotch_demo/scotch_dashboard.ipynb
etc/notebooks/index.ipynb

* Update docker image ref and other related commands in Makefile
* Install latest stable decl widgets instead of local build by default
* Update got scotch demo for ipywidgets 5.1.x
Fixes #245

Move dev env to notebook 4.2 by default

---

Makefile
etc/notebooks/community_sentiment_demo/community_sentiment_demo.ipynb
etc/notebooks/got_scotch_demo/scotch_dashboard_declarative.ipynb
etc/notebooks/meetup_outreach_demo/meetup-outreach.ipynb
etc/notebooks/resizable_widgets_tutorial/resizable_widgets.ipynb
etc/notebooks/sentiment_boilerplate_demo/sentiment_boilerplate_demo.ipynb
etc/notebooks/stream_demo/meetup-streaming.ipynb
etc/notebooks/taxi_demo/taxi_dashboard.ipynb
etc/notebooks/test/test_layout_declarativewidgets.ipynb

Update Notebooks to be compatible with declwidgets 0.6.0

---

README.md

Simplify README, refer to RTD

---

docs/source/getting-started.md

Fixes https://github.com/jupyter-incubator/dashboards/issues/272

Add uninstall instructions for version 0.4
